// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dkmjylfwcnlzdadniwen.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRrbWp5bGZ3Y25semRhZG5pd2VuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjAzODc2MzksImV4cCI6MjA3NTk2MzYzOX0.H0DApNWE6ZQSbyqwCiXhmWFEyPQymoeHqHBemTwDs4o";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});