-- Create environment_data table
CREATE TABLE IF NOT EXISTS public.environment_data (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  co2_ppm REAL,
  air_quality_ppm REAL,
  co_ppm REAL,
  smoke_ppm REAL,
  flame_detected BOOLEAN,
  motion_detected BOOLEAN,
  relay_on BOOLEAN
);

-- Enable RLS
ALTER TABLE public.environment_data ENABLE ROW LEVEL SECURITY;

-- Create policies (public read/write for now - can be restricted later)
CREATE POLICY "Allow public read on environment_data" ON public.environment_data FOR SELECT USING (true);
CREATE POLICY "Allow public insert on environment_data" ON public.environment_data FOR INSERT WITH CHECK (true);
CREATE POLICY "Allow public update on environment_data" ON public.environment_data FOR UPDATE USING (true);

-- Create index on created_at for faster queries
CREATE INDEX IF NOT EXISTS idx_environment_data_created_at ON public.environment_data(created_at DESC);

-- Insert some sample data
INSERT INTO public.environment_data (co2_ppm, air_quality_ppm, co_ppm, smoke_ppm, flame_detected, motion_detected, relay_on)
VALUES 
  (420, 35, 3.2, 30, false, false, false),
  (650, 28, 2.8, 25, false, false, false),
  (800, 45, 5.0, 50, false, true, false);
